#!/bin/bash

for staged_file in $(git diff --cached --name-only); do
    echo "Formatting ${staged_file}..."
    autopep8 -i "${staged_file}"
    yapf -i "${staged_file}"
    git add "${staged_file}"
done

exit 0
