name: Format enforcer and Flake8 linting

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  format_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install YAPF, autope8 and flake8
        run: |
          pip install yapf autopep8 flake8 pre-commit
          pre-commit install

      - name: Run Flake8
        run: flake8

      - name: Check formatting
        run: |
          SKIP=flake8 pre-commit run -a
      - name: Check for changes
        run: git diff --exit-code --name-only || (echo "Code is not formatted correctly. Please run formatter locally on the files above." && exit 1)
