name: Pre-commit Workflow

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit and capture changes
      run: |
        pre-commit run --all-files || true
        git_diff=$(git diff)
        if [ -n "$git_diff" ]; then
          echo "Changes detected. Committing and pushing..."
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Pre-commit fixes (GitHub Actions)"
          git push ${{ github.head_ref }}
        else
          echo "No changes to commit."
        fi
