name: Pre-commit Workflow

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit
      run: |
        SKIP=flake8 pre-commit run --all-files

    - name: Check if there are changes to commit
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Pre-commit fixes (GitHub Actions)"
          git push
        else
          echo "No changes to commit."
        fi
